// source: Header.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.cloud.office.customer.busi.imserver.protocol.Header', null, global);
goog.exportSymbol('proto.com.cloud.office.customer.busi.imserver.protocol.Header.MessageType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.cloud.office.customer.busi.imserver.protocol.Header, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.cloud.office.customer.busi.imserver.protocol.Header.displayName = 'proto.com.cloud.office.customer.busi.imserver.protocol.Header';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.toObject = function(opt_includeInstance) {
  return proto.com.cloud.office.customer.busi.imserver.protocol.Header.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.Header} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.toObject = function(includeInstance, msg) {
  var f, obj = {
    magicNumber: jspb.Message.getFieldWithDefault(msg, 1, 0),
    version: jspb.Message.getFieldWithDefault(msg, 2, 0),
    messageType: jspb.Message.getFieldWithDefault(msg, 3, 0),
    messageLength: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.Header}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.cloud.office.customer.busi.imserver.protocol.Header;
  return proto.com.cloud.office.customer.busi.imserver.protocol.Header.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.Header} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.Header}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMagicNumber(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMessageType(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMessageLength(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.cloud.office.customer.busi.imserver.protocol.Header.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.Header} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMagicNumber();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getMessageType();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getMessageLength();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.MessageType = {
  SEND_MESSAGE_REQUEST: 0,
  SEND_MESSAGE_RESPONSE: 1
};

/**
 * optional uint32 magic_number = 1;
 * @return {number}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.getMagicNumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.Header} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.setMagicNumber = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 version = 2;
 * @return {number}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.getVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.Header} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.setVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 message_type = 3;
 * @return {number}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.getMessageType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.Header} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.setMessageType = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 message_length = 4;
 * @return {number}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.getMessageLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.Header} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.Header.prototype.setMessageLength = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


goog.object.extend(exports, proto.com.cloud.office.customer.busi.imserver.protocol);
