// source: MessageProtoBuf.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var Header_pb = require('./Header_pb.js');
goog.object.extend(proto, Header_pb);
goog.exportSymbol('proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage', null, global);
goog.exportSymbol('proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.BodyCase', null, global);
goog.exportSymbol('proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest', null, global);
goog.exportSymbol('proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.DataType', null, global);
goog.exportSymbol('proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse', null, global);
goog.exportSymbol('proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.Status', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.oneofGroups_);
};
goog.inherits(proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.displayName = 'proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.displayName = 'proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.displayName = 'proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.BodyCase = {
  BODY_NOT_SET: 0,
  SEND_MESSAGE_REQUEST: 2,
  SEND_MESSAGE_RESPONSE: 3
};

/**
 * @return {proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.BodyCase}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.getBodyCase = function() {
  return /** @type {proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.BodyCase} */(jspb.Message.computeOneofCase(this, proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && Header_pb.Header.toObject(includeInstance, f),
    sendMessageRequest: (f = msg.getSendMessageRequest()) && proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.toObject(includeInstance, f),
    sendMessageResponse: (f = msg.getSendMessageResponse()) && proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage;
  return proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Header_pb.Header;
      reader.readMessage(value,Header_pb.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest;
      reader.readMessage(value,proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.deserializeBinaryFromReader);
      msg.setSendMessageRequest(value);
      break;
    case 3:
      var value = new proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse;
      reader.readMessage(value,proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.deserializeBinaryFromReader);
      msg.setSendMessageResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Header_pb.Header.serializeBinaryToWriter
    );
  }
  f = message.getSendMessageRequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.serializeBinaryToWriter
    );
  }
  f = message.getSendMessageResponse();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional Header header = 1;
 * @return {?proto.com.cloud.office.customer.busi.imserver.protocol.Header}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.getHeader = function() {
  return /** @type{?proto.com.cloud.office.customer.busi.imserver.protocol.Header} */ (
    jspb.Message.getWrapperField(this, Header_pb.Header, 1));
};


/**
 * @param {?proto.com.cloud.office.customer.busi.imserver.protocol.Header|undefined} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage} returns this
*/
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SendMessageRequest send_message_request = 2;
 * @return {?proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.getSendMessageRequest = function() {
  return /** @type{?proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} */ (
    jspb.Message.getWrapperField(this, proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest, 2));
};


/**
 * @param {?proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest|undefined} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage} returns this
*/
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.setSendMessageRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.clearSendMessageRequest = function() {
  return this.setSendMessageRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.hasSendMessageRequest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional SendMessageResponse send_message_response = 3;
 * @return {?proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.getSendMessageResponse = function() {
  return /** @type{?proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse} */ (
    jspb.Message.getWrapperField(this, proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse, 3));
};


/**
 * @param {?proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse|undefined} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage} returns this
*/
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.setSendMessageResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.clearSendMessageResponse = function() {
  return this.setSendMessageResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.ImMessage.prototype.hasSendMessageResponse = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && Header_pb.Header.toObject(includeInstance, f),
    senderId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    receiverId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    timestamp: jspb.Message.getFieldWithDefault(msg, 4, 0),
    content: msg.getContent_asB64(),
    dataType: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest;
  return proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Header_pb.Header;
      reader.readMessage(value,Header_pb.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setReceiverId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTimestamp(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setContent(value);
      break;
    case 6:
      var value = /** @type {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.DataType} */ (reader.readEnum());
      msg.setDataType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Header_pb.Header.serializeBinaryToWriter
    );
  }
  f = message.getSenderId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getReceiverId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getContent_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getDataType();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.DataType = {
  TEXT: 0,
  IMAGE: 1,
  AUDIO: 2,
  VIDEO: 3
};

/**
 * optional Header header = 1;
 * @return {?proto.com.cloud.office.customer.busi.imserver.protocol.Header}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.getHeader = function() {
  return /** @type{?proto.com.cloud.office.customer.busi.imserver.protocol.Header} */ (
    jspb.Message.getWrapperField(this, Header_pb.Header, 1));
};


/**
 * @param {?proto.com.cloud.office.customer.busi.imserver.protocol.Header|undefined} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} returns this
*/
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string sender_id = 2;
 * @return {string}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.getSenderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.setSenderId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string receiver_id = 3;
 * @return {string}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.getReceiverId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.setReceiverId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 timestamp = 4;
 * @return {number}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bytes content = 5;
 * @return {!(string|Uint8Array)}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.getContent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes content = 5;
 * This is a type-conversion wrapper around `getContent()`
 * @return {string}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.getContent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getContent()));
};


/**
 * optional bytes content = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getContent()`
 * @return {!Uint8Array}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.getContent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getContent()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.setContent = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * optional DataType data_type = 6;
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.DataType}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.getDataType = function() {
  return /** @type {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.DataType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.DataType} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageRequest.prototype.setDataType = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    header: (f = msg.getHeader()) && Header_pb.Header.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 2, 0),
    message: jspb.Message.getFieldWithDefault(msg, 3, ""),
    messageId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse;
  return proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Header_pb.Header;
      reader.readMessage(value,Header_pb.Header.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessageId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Header_pb.Header.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMessageId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.Status = {
  SUCCESS: 0,
  FAILURE: 1
};

/**
 * optional Header header = 1;
 * @return {?proto.com.cloud.office.customer.busi.imserver.protocol.Header}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.getHeader = function() {
  return /** @type{?proto.com.cloud.office.customer.busi.imserver.protocol.Header} */ (
    jspb.Message.getWrapperField(this, Header_pb.Header, 1));
};


/**
 * @param {?proto.com.cloud.office.customer.busi.imserver.protocol.Header|undefined} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse} returns this
*/
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Status status = 2;
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.Status}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.getStatus = function() {
  return /** @type {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.Status} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.Status} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string message = 3;
 * @return {string}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string message_id = 4;
 * @return {string}
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.getMessageId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse} returns this
 */
proto.com.cloud.office.customer.busi.imserver.protocol.SendMessageResponse.prototype.setMessageId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.com.cloud.office.customer.busi.imserver.protocol);
