// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Header.proto

package com.cloud.office.customer.busi.imserver.protocol;

public final class HeaderProto {
  private HeaderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cloud.office.customer.busi.imserver.protocol.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 魔数，用于校验协议是否匹配
     * </pre>
     *
     * <code>uint32 magic_number = 1;</code>
     * @return The magicNumber.
     */
    int getMagicNumber();

    /**
     * <pre>
     * 协议版本号，用于兼容旧协议
     * </pre>
     *
     * <code>uint32 version = 2;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <pre>
     * 消息类型，用于区分不同类型的消息
     * </pre>
     *
     * <code>uint32 message_type = 3;</code>
     * @return The messageType.
     */
    int getMessageType();

    /**
     * <pre>
     * 消息体长度，单位为字节
     * </pre>
     *
     * <code>uint32 message_length = 4;</code>
     * @return The messageLength.
     */
    int getMessageLength();
  }
  /**
   * Protobuf type {@code com.cloud.office.customer.busi.imserver.protocol.Header}
   */
  public static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.cloud.office.customer.busi.imserver.protocol.Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Header();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              magicNumber_ = input.readUInt32();
              break;
            }
            case 16: {

              version_ = input.readUInt32();
              break;
            }
            case 24: {

              messageType_ = input.readUInt32();
              break;
            }
            case 32: {

              messageLength_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cloud.office.customer.busi.imserver.protocol.HeaderProto.internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cloud.office.customer.busi.imserver.protocol.HeaderProto.internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header.class, com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header.Builder.class);
    }

    /**
     * <pre>
     * 消息类型编号
     * </pre>
     *
     * Protobuf enum {@code com.cloud.office.customer.busi.imserver.protocol.Header.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SEND_MESSAGE_REQUEST = 0;</code>
       */
      SEND_MESSAGE_REQUEST(0),
      /**
       * <code>SEND_MESSAGE_RESPONSE = 1;</code>
       */
      SEND_MESSAGE_RESPONSE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SEND_MESSAGE_REQUEST = 0;</code>
       */
      public static final int SEND_MESSAGE_REQUEST_VALUE = 0;
      /**
       * <code>SEND_MESSAGE_RESPONSE = 1;</code>
       */
      public static final int SEND_MESSAGE_RESPONSE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return SEND_MESSAGE_REQUEST;
          case 1: return SEND_MESSAGE_RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.cloud.office.customer.busi.imserver.protocol.Header.MessageType)
    }

    public static final int MAGIC_NUMBER_FIELD_NUMBER = 1;
    private int magicNumber_;
    /**
     * <pre>
     * 魔数，用于校验协议是否匹配
     * </pre>
     *
     * <code>uint32 magic_number = 1;</code>
     * @return The magicNumber.
     */
    @java.lang.Override
    public int getMagicNumber() {
      return magicNumber_;
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <pre>
     * 协议版本号，用于兼容旧协议
     * </pre>
     *
     * <code>uint32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 3;
    private int messageType_;
    /**
     * <pre>
     * 消息类型，用于区分不同类型的消息
     * </pre>
     *
     * <code>uint32 message_type = 3;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public int getMessageType() {
      return messageType_;
    }

    public static final int MESSAGE_LENGTH_FIELD_NUMBER = 4;
    private int messageLength_;
    /**
     * <pre>
     * 消息体长度，单位为字节
     * </pre>
     *
     * <code>uint32 message_length = 4;</code>
     * @return The messageLength.
     */
    @java.lang.Override
    public int getMessageLength() {
      return messageLength_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (magicNumber_ != 0) {
        output.writeUInt32(1, magicNumber_);
      }
      if (version_ != 0) {
        output.writeUInt32(2, version_);
      }
      if (messageType_ != 0) {
        output.writeUInt32(3, messageType_);
      }
      if (messageLength_ != 0) {
        output.writeUInt32(4, messageLength_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (magicNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, magicNumber_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, version_);
      }
      if (messageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, messageType_);
      }
      if (messageLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, messageLength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header)) {
        return super.equals(obj);
      }
      com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header other = (com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header) obj;

      if (getMagicNumber()
          != other.getMagicNumber()) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (getMessageType()
          != other.getMessageType()) return false;
      if (getMessageLength()
          != other.getMessageLength()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAGIC_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMagicNumber();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType();
      hash = (37 * hash) + MESSAGE_LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getMessageLength();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cloud.office.customer.busi.imserver.protocol.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cloud.office.customer.busi.imserver.protocol.Header)
        com.cloud.office.customer.busi.imserver.protocol.HeaderProto.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cloud.office.customer.busi.imserver.protocol.HeaderProto.internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cloud.office.customer.busi.imserver.protocol.HeaderProto.internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header.class, com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header.Builder.class);
      }

      // Construct using com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        magicNumber_ = 0;

        version_ = 0;

        messageType_ = 0;

        messageLength_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cloud.office.customer.busi.imserver.protocol.HeaderProto.internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_descriptor;
      }

      @java.lang.Override
      public com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header getDefaultInstanceForType() {
        return com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header.getDefaultInstance();
      }

      @java.lang.Override
      public com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header build() {
        com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header buildPartial() {
        com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header result = new com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header(this);
        result.magicNumber_ = magicNumber_;
        result.version_ = version_;
        result.messageType_ = messageType_;
        result.messageLength_ = messageLength_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header) {
          return mergeFrom((com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header other) {
        if (other == com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header.getDefaultInstance()) return this;
        if (other.getMagicNumber() != 0) {
          setMagicNumber(other.getMagicNumber());
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getMessageType() != 0) {
          setMessageType(other.getMessageType());
        }
        if (other.getMessageLength() != 0) {
          setMessageLength(other.getMessageLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int magicNumber_ ;
      /**
       * <pre>
       * 魔数，用于校验协议是否匹配
       * </pre>
       *
       * <code>uint32 magic_number = 1;</code>
       * @return The magicNumber.
       */
      @java.lang.Override
      public int getMagicNumber() {
        return magicNumber_;
      }
      /**
       * <pre>
       * 魔数，用于校验协议是否匹配
       * </pre>
       *
       * <code>uint32 magic_number = 1;</code>
       * @param value The magicNumber to set.
       * @return This builder for chaining.
       */
      public Builder setMagicNumber(int value) {
        
        magicNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 魔数，用于校验协议是否匹配
       * </pre>
       *
       * <code>uint32 magic_number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMagicNumber() {
        
        magicNumber_ = 0;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       * 协议版本号，用于兼容旧协议
       * </pre>
       *
       * <code>uint32 version = 2;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * 协议版本号，用于兼容旧协议
       * </pre>
       *
       * <code>uint32 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议版本号，用于兼容旧协议
       * </pre>
       *
       * <code>uint32 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int messageType_ ;
      /**
       * <pre>
       * 消息类型，用于区分不同类型的消息
       * </pre>
       *
       * <code>uint32 message_type = 3;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <pre>
       * 消息类型，用于区分不同类型的消息
       * </pre>
       *
       * <code>uint32 message_type = 3;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型，用于区分不同类型的消息
       * </pre>
       *
       * <code>uint32 message_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private int messageLength_ ;
      /**
       * <pre>
       * 消息体长度，单位为字节
       * </pre>
       *
       * <code>uint32 message_length = 4;</code>
       * @return The messageLength.
       */
      @java.lang.Override
      public int getMessageLength() {
        return messageLength_;
      }
      /**
       * <pre>
       * 消息体长度，单位为字节
       * </pre>
       *
       * <code>uint32 message_length = 4;</code>
       * @param value The messageLength to set.
       * @return This builder for chaining.
       */
      public Builder setMessageLength(int value) {
        
        messageLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息体长度，单位为字节
       * </pre>
       *
       * <code>uint32 message_length = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageLength() {
        
        messageLength_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.cloud.office.customer.busi.imserver.protocol.Header)
    }

    // @@protoc_insertion_point(class_scope:com.cloud.office.customer.busi.imserver.protocol.Header)
    private static final com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header();
    }

    public static com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @java.lang.Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cloud.office.customer.busi.imserver.protocol.HeaderProto.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Header.proto\0220com.cloud.office.custome" +
      "r.busi.imserver.protocol\"\241\001\n\006Header\022\024\n\014m" +
      "agic_number\030\001 \001(\r\022\017\n\007version\030\002 \001(\r\022\024\n\014me" +
      "ssage_type\030\003 \001(\r\022\026\n\016message_length\030\004 \001(\r" +
      "\"B\n\013MessageType\022\030\n\024SEND_MESSAGE_REQUEST\020" +
      "\000\022\031\n\025SEND_MESSAGE_RESPONSE\020\001B?\n0com.clou" +
      "d.office.customer.busi.imserver.protocol" +
      "B\013HeaderProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_cloud_office_customer_busi_imserver_protocol_Header_descriptor,
        new java.lang.String[] { "MagicNumber", "Version", "MessageType", "MessageLength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
